# Generated by Django 3.0.3 on 2020-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_mpaa_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(choices=[('-', 'Brak'), ('G', 'Rating G'), ('PG-13', 'Rating PG-13'), ('NC-17', 'Rating NC-17')], default='G', max_length=5),
        ),
    ]
